[workspace]
authors = ["Adam D. Hines <adam.hines@qut.edu.au>, Gokul B. Nair, Nicolas Guillermo Marticorena Vidal, Michael Milford, Tobias Fischer"]
channels = ["conda-forge", "adamhines"]
name = "EventGeM"
platforms = [
    { platform = "linux-64", cuda = "12", glibc = "2.35" },
    { platform = "linux-aarch64", cuda = "12", glibc = "2.35" },
]
version = "0.1.0"

[tasks]
eventgem = {cmd = "pixi run python3 main.py"}

inference = {cmd = "pixi run python3 eventgem/inference.py"}
inference-jetson = {cmd = "pixi run python3 eventgem/inference-jetson.py"}

demo = {cmd = "pixi run python3 main.py --dataset brisbane_event --reference sunset2 --query sunset1 --start-time 1587452582.35 --skip 20 --stream --demo"}

# Paper specific comparisons
sunset2-sunset1 = {cmd = "pixi run eventgem -d brisbane_event -r sunset2 -q sunset1 --data-root /media/adam/vprdatasets/eventgem --feature-out /media/adam/vprdatasets/eventgem/features --keypoint-out /media/adam/vprdatasets/eventgem/keypoints --ref-offset 1587540271650 --query-offset 1587452582350"}
sunset2-morning = {cmd = "pixi run eventgem -d brisbane_event -r sunset2 -q morning --data-root /media/adam/vprdatasets/eventgem --feature-out /media/adam/vprdatasets/eventgem/features --keypoint-out /media/adam/vprdatasets/eventgem/keypoints --ref-offset 1587540271650 --query-offset 1588029265730"}
sunset2-daytime = {cmd = "pixi run eventgem -d brisbane_event -r sunset2 -q daytime --data-root /media/adam/vprdatasets/eventgem --feature-out /media/adam/vprdatasets/eventgem/features --keypoint-out /media/adam/vprdatasets/eventgem/keypoints --ref-offset 1587540271650 --query-offset 1587705130800"}
sunset2-sunrise = {cmd = "pixi run eventgem -d brisbane_event -r sunset2 -q sunrise --data-root /media/adam/vprdatasets/eventgem --feature-out /media/adam/vprdatasets/eventgem/features --keypoint-out /media/adam/vprdatasets/eventgem/keypoints --ref-offset 1587540271650 --query-offset 1588105232910"}
sunset2-night = {cmd = "pixi run eventgem -d brisbane_event -r sunset2 -q night --data-root /media/adam/vprdatasets/eventgem --feature-out /media/adam/vprdatasets/eventgem/features --keypoint-out /media/adam/vprdatasets/eventgem/keypoints --ref-offset 1587540271650 --query-offset 1587975221100"}


R0FA0-R0FS0 = {cmd = "pixi run eventgem -d nsavp -r R0_FA0 -q R0_FS0 --data-root /media/adam/vprdatasets/eventgem --feature-out /media/adam/vprdatasets/eventgem/features --keypoint-out /media/adam/vprdatasets/eventgem/keypoints"}
R0FA0-R1DA0 = {cmd = "pixi run eventgem -d nsavp -r R0_FA0 -q R1_DA0 --data-root /media/adam/vprdatasets/eventgem --feature-out /media/adam/vprdatasets/eventgem/features --keypoint-out /media/adam/vprdatasets/eventgem/keypoints"}
R0FA0-R1FA0 = {cmd = "pixi run eventgem -d nsavp -r R0_FA0 -q R1_FA0 --data-root /media/adam/vprdatasets/eventgem --feature-out /media/adam/vprdatasets/eventgem/features --keypoint-out /media/adam/vprdatasets/eventgem/keypoints"}

[dependencies]
python = "=3.12"
numpy = "*"
pytorch = "*"
pandas = "*"
sinabs = "*"
torchvision = "*"
yaml = "*"
pyyaml = "*"
opencv = "*"
tqdm = "*"
scikit-learn = "*"
pynmea2 = "*"
pyarrow = "*"
cmapy = "*"
contourpy = "*"
cycler = "*"
filelock = "*"
fonttools = "*" 
fsspec = "*"
h5py = "*"
hdf5plugin = "*"
imageio = "*"
Jinja2 = "*"
joblib = "*"
kiwisolver = "*"
kornia = "*"
lazy_loader = "*"
llvmlite = "*"
MarkupSafe = "*"
matplotlib = "*"
mpmath = "*"
networkx = "*"
numba = "*"
packaging = "*"
pillow = "*"
pyparsing = "*"
python-dateutil = "*"
scikit-image = "*"
scipy = "*"
six = "*"
sympy = "*"
threadpoolctl = "*"
tifffile = "*"
triton = "*"
typing_extensions = "*"
prettytable = "*"
cuda-version = "12.*"
cuda-cudart-dev = "*"
cuda-crt = "*"
cudnn = "*"
libcusparse-dev = "*"
cuda-driver-dev = "*"
cuda-nvcc = "*"
cuda-nvrtc-dev = "*"
cuda-nvtx-dev = "*"
cuda-nvml-dev = "*"
cuda-profiler-api = "*"
cusparselt = "*"
libcublas-dev = "*"
libcudss-dev = "*"
libcufile-dev = "*"
libcufft-dev = "*"
libcurand-dev = "*"
libcusolver-dev = "*"
onnxscript = "*"
eventcv = "*"
loguru = "*"
requests = "*"
