[workspace]
authors = ["Adam D. Hines <adam.hines@qut.edu.au>, Gokul B. Nair, Nicolas Guillermo Marticorena Vidal, Michael Milford, Tobias Fischer"]
channels = ["conda-forge", "adamhines"]
name = "EventGeM"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[system-requirements]
cuda = "12"
libc = {family="glibc", version="2.35"}

[tasks]
inference = {cmd = "pixi run python3 eventgem/inference.py"}
inference-jetson = {cmd = "pixi run python3 eventgem/inference-jetson.py"}

install-trt = "pip install --extra-index-url https://pypi.nvidia.com tensorrt-cu12"

[target.linux-64.dependencies]
python = ">3.8"
numpy = "*"
pytorch = "*"
sinabs = "*"
torchvision = "*"
pytorch-lightning  = "*"
einops = "*"
timm = "*"
yaml = "*"
pyyaml = "*"
flatten-dict = "*"
opencv = "*"
tqdm = "*"
scikit-learn = "*"
pynmea2 = "*"
pyarrow = "*"
cmapy = "*"
contourpy = "*"
cycler = "*"
filelock = "*"
fonttools = "*" 
fsspec = "*"
h5py = "*"
hdf5plugin = "*"
imageio = "*"
Jinja2 = "*"
joblib = "*"
kiwisolver = "*"
kornia = "*"
lazy_loader = "*"
llvmlite = "*"
MarkupSafe = "*"
matplotlib = "*"
mpmath = "*"
networkx = "*"
numba = "*"
packaging = "*"
pillow = "*"
pyparsing = "*"
python-dateutil = "*"
scikit-image = "*"
scipy = "*"
six = "*"
sympy = "*"
threadpoolctl = "*"
tifffile = "*"
triton = "*"
typing_extensions = "*"
prettytable = "*"
cuda-version = "12.*"
cuda-cudart-dev = "*"
cuda-crt = "*"
cudnn = "*"
libcusparse-dev = "*"
cuda-driver-dev = "*"
cuda-nvcc = "*"
cuda-nvrtc-dev = "*"
cuda-nvtx-dev = "*"
cuda-nvml-dev = "*"
cuda-profiler-api = "*"
cusparselt = "*"
libcublas-dev = "*"
libcudss-dev = "*"
libcufile-dev = "*"
libcufft-dev = "*"
libcurand-dev = "*"
libcusolver-dev = "*"

[target.linux-aarch64.dependencies]
python = "*"
numpy = "*"
pytorch = {version = "*", channel = "adamhines"}
libtorch = {version = "*", channel = "adamhines"}
sinabs = "*"
torchvision = {version = "*", channel = "adamhines"}
pytorch-lightning  = "*"
einops = "*"
timm = "*"
yaml = "*"
pyyaml = "*"
flatten-dict = "*"
opencv = "*"
tqdm = "*"
scikit-learn = "*"
pynmea2 = "*"
pyarrow = "*"
cmapy = "*"
contourpy = "*"
cycler = "*"
filelock = "*"
fonttools = "*" 
fsspec = "*"
h5py = "*"
hdf5plugin = "*"
imageio = "*"
Jinja2 = "*"
joblib = "*"
kiwisolver = "*"
kornia = "*"
lazy_loader = "*"
llvmlite = "*"
MarkupSafe = "*"
matplotlib = "*"
mpmath = "*"
networkx = "*"
numba = "*"
packaging = "*"
pillow = "*"
pyparsing = "*"
python-dateutil = "*"
scikit-image = "*"
scipy = "*"
six = "*"
sympy = "*"
threadpoolctl = "*"
tifffile = "*"
triton = "*"
typing_extensions = "*"
prettytable = "*"
onnxscript = "*"

[pypi-dependencies]
dv-processing = "*"
